[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "inv"
description = ''
readme = "README.md"
requires-python = ">=3.12"
license = "MIT"
keywords = []
authors = [
  { name = "Matt Koski", email = "maccam912@gmail.com" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
  "click",
  "sqlalchemy>=2.0.0",
  "textual>=0.52.0",
]
dynamic = ["version"]

[project.urls]
Documentation = "https://github.com/unknown/inv#readme"
Issues = "https://github.com/unknown/inv/issues"
Source = "https://github.com/unknown/inv"

[project.scripts]
inv = "inv.cli:inv"

[tool.hatch.version]
path = "inv/__about__.py"

[tool.hatch.envs.default]
dependencies = [
  "pytest",
  "pytest-cov",
  "ruff",
  "mypy",
]
[tool.hatch.envs.default.scripts]
cov = "pytest --cov-report=term-missing --cov-config=pyproject.toml --cov=inv --cov=tests {args}"
no-cov = "cov --no-cov {args}"
lint = "ruff check inv tests {args}"
format = "ruff format inv tests {args}"
typecheck = "mypy inv tests {args}"
fixup = ["ruff check inv tests --fix", "ruff format inv tests"]
check = ["format", "lint", "typecheck", "cov"]

[[tool.hatch.envs.test.matrix]]
python = ["312"]

[tool.coverage.run]
branch = true
parallel = true
omit = [
  "inv/__about__.py",
]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]

[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = ["E", "F", "W", "I", "UP", "PL", "TID"]
ignore = ["E501"]

[tool.ruff.format]
quote-style = "double"

[tool.mypy]
python_version = "3.12"
warn_return_any = true
warn_unused_configs = true
ignore_missing_imports = true
